'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NOTARIA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM usuario  WHERE nombre = @name.
        '''</summary>
        Friend ReadOnly Property deleteUserByName() As String
            Get
                Return ResourceManager.GetString("deleteUserByName", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Forward() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property gui_secondbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gui_secondbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Home() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO aplicacionrole (idrol,idaplicacion) VALUES(@idRol, @idAplication).
        '''</summary>
        Friend ReadOnly Property insertAplicationRol() As String
            Get
                Return ResourceManager.GetString("insertAplicationRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO rol (tiporol) VALUES(@tipoRol).
        '''</summary>
        Friend ReadOnly Property insertRol() As String
            Get
                Return ResourceManager.GetString("insertRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO usuario (nombre, password,idrol) VALUES(@name, @pass, @idrol).
        '''</summary>
        Friend ReadOnly Property insertUser() As String
            Get
                Return ResourceManager.GetString("insertUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT *  FROM aplicacion a.
        '''</summary>
        Friend ReadOnly Property selectApplication() As String
            Get
                Return ResourceManager.GetString("selectApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT distinct (a.idaplicacion) FROM aplicacion a, rol r, aplicacionrole ar where ar.idrol = 1 and ar.idaplicacion = a.idaplicacion.
        '''</summary>
        Friend ReadOnly Property selectApplicationRole() As String
            Get
                Return ResourceManager.GetString("selectApplicationRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM rol WHERE tiporol =@tipoRol.
        '''</summary>
        Friend ReadOnly Property selectRolByTipoRol() As String
            Get
                Return ResourceManager.GetString("selectRolByTipoRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT r.tiporol FROM rol r.
        '''</summary>
        Friend ReadOnly Property selectRoltipo() As String
            Get
                Return ResourceManager.GetString("selectRoltipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT r.tiporol FROM rol r WHERE r.idrol = @idRol.
        '''</summary>
        Friend ReadOnly Property selectRolTipoRolByIdRol() As String
            Get
                Return ResourceManager.GetString("selectRolTipoRolByIdRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM usuario.
        '''</summary>
        Friend ReadOnly Property selectUser() As String
            Get
                Return ResourceManager.GetString("selectUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT u.nombre FROM usuario u WHERE u.idrol = @idRol.
        '''</summary>
        Friend ReadOnly Property selectUserByIdRol() As String
            Get
                Return ResourceManager.GetString("selectUserByIdRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM usuario u WHERE u.nombre = @name.
        '''</summary>
        Friend ReadOnly Property selectUserByNombre() As String
            Get
                Return ResourceManager.GetString("selectUserByNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT nombre FROM usuario.
        '''</summary>
        Friend ReadOnly Property selectUserNombre() As String
            Get
                Return ResourceManager.GetString("selectUserNombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE usuario SET nombre = @newName, password = @pass, idrol = @idRol WHERE nombre = @oldName.
        '''</summary>
        Friend ReadOnly Property updateUserByName() As String
            Get
                Return ResourceManager.GetString("updateUserByName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
